# Generated by Django 2.1.5 on 2019-02-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190131_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default=False, upload_to='my_images'),
        ),
    ]
